{
    'name': 'IT Parc - Gestion de Parc Informatique',
    'version': '18.0.1.0.0',
    'category': 'Tools',
    'summary': 'Gestion complète du parc informatique TECHPARK CI',
    'author': 'TECHPARK CI',
    'depends': ['base', 'hr', 'mail', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequences.xml',
        'data/cron.xml',
        'data/it_parc_demo.xml',
        'views/dashboard_action.xml',
        'views/menu.xml',
        'views/it_equipement_views.xml',
        'views/it_intervention_views.xml',
        'views/it_contrat_views.xml',
        'views/it_alerte_views.xml',
        'views/wizard_views.xml',
        'views/wizard_import_views.xml',
        'views/export_excel_views.xml',
        'report/report_fiche_equipement.xml',
        'report/report_inventaire.xml',
        'report/report_maintenances.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_parc/static/src/js/dashboard.js',
            'it_parc/static/src/xml/dashboard.xml',
            'it_parc/static/src/css/dashboard.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
